### ISSUE TITLE
Improper rendering and lagging when using GUI style: qt5ct-style

### ISSUE THREAD

**Issue by Shoegzer** [qmc2/qmc2-mame-fe#11]
After selecting GUI stye: qt5ct-style in Front end > GUI, QMC2 renders certain artifacts improperly, and lags while attempting to do so.  For example, the "Name" column under the "Software List" tab, as shown on the far right of this screenshot: 

![pic](https://user-images.githubusercontent.com/12475371/163260144-952f7fc9-2a17-4250-917b-0778f18b8bb6.png)

Other GUI styles such as "cleanlooks" do not exhibit this issue.

As this is the only dark theme pre-packaged with QMC2 it would be nice to have this working properly.  I'm happy to supply any further information or testing needed.

Information:
* OS: Linux Mint 20.3 / kernel 5.13
* Compiled with: gcc 11.1.0
* Qt Version: 5.12.8
* QMC2 Version: fd97380b0291d6ee1f9f50c5440456089928e1f5

**Comment by qmc2** [comment]
When that doesn't happen with another style like cleanlooks, I actually don't see the mistake on my end... but I'll have a look, although QMC2 isn't doing anything special here.

What do you mean with "as this is the only dark theme pre-packaged with QMC2"? QMC2 doesn't come with any pre-packaged themes. It only shows the themes that are available / installed. There are a number of themes that come with Qt, for example "cleanlooks", "plastique", "fusion" and a few others. But no "dark" one.

**Comment by Shoegzer** [comment]
Ah, I see - I had assumed those themes are pre-packaged with QMC2 when they are in fact part of the Qt distribution, so you can disregard my comment.  I agree this may not be a QMC2-specific issue and perhaps a bug in the theme itself, but thanks for any insight you may have.

In case it helps, I tested the following installed GUI style options:

* Default
* cleanlooks
* gtk2
* cde
* motif
* plastique
* qt5-ctstyle
* Windows
* Fusion

All worked fine except for Default, gtk2 and qt5-ctstyle.  Each of those three were "dark" themes and appeared to be the same, so they exhibited the issue I described above.  I'm guessing "Default" is just reflecting my system preference to use the dark theme.

**Comment by qmc2** [comment]
All I can say is that "we" had those issues back in the early Qt 4 days already, and although new styles are developed. they come with similar issues :)... some are quite good, though. I'm talking of community-made styles (I have many more installed)... the ones that come with Qt should be okay, but not gtk2 as far as I remember. qt5-ctstyle is new to me. Anyway, the styles have their pros and cons, especially when used **together** with the style-sheet (i.e. the ones from QMC's site).

I'll close the issue. But we can still comment.

**Comment by qmc2** [comment]
Also, you can set the style to **default** and put the style you want on the command... for example:

`qmc2-sdlmame -style=Fusion`

This uses a different way of loading a style (Qt internal) and may show different result. But I don't know in your case...

**Comment by Shoegzer** [comment]
Thanks!  Actually it's "qt5ct-style" and not "qt5-ctstyle".  I changed my earlier post for accuracy.

Changing to Default and then using qt5ct-style at commandline produces the same negative result unfortunately.  Thanks for the link though, I see the reference to commandline args and didn't realize you could do -style or -stylesheet for any supporting Qt app.  Cool.

The styles I'm using and noted above are all from the stock Qt5 distro apparently, as I've not installed any community-made styles of my own, nor do I use a QMC2 style sheet that I'm aware of.  It's too bad that the three dark styles available all exhibit the same issue, QMC2 looks really nice with a dark theme.  

I have some hope that compiling with my Qt 6.3.0 install will help, though I'm not sure why my script to change Qt at compile-time isn't working (QMC2 still shows Qt 5.12.8 even when I use it).  Separate issue though.
