### ISSUE TITLE
[Feature request] Support for XML format

### ISSUE THREAD

**Issue by Shoegzer** [qmc2/qmc2-mame-fe#17]
This would permit parsing/displaying data structured in the newer XML format supported in MAME for certain assets.  For example with the [history](https://www.arcade-history.com/index.php?page=download) asset.  Thanks!

**Comment by qmc2** [comment]
Will do!

**Comment by linuxsynth** [comment]
I would like this feature too!

**Comment by belegdol** [comment]
Fixed in 9581f69fbde2b9733535bc37b1972233889fd8fc.

**Comment by Shoegzer** [comment]
Thanks so much @belegdol.  Tested and working well here on my custom build.  Closing.
