### ISSUE TITLE
project alive?

### ISSUE THREAD

**Issue by ghost** [qmc2/qmc2-mame-fe#20]
Hi

Is this project still alive?
Many MAME updates since the last version of qmc2 available by download here are missing.
Latest version is 0.243 and then suddenly no updates anymore.

Thank you

**Comment by qmc2** [comment]
Could you be more precise, please. What's exactly new to MAME that QMC2 "must" support?

**Comment by cuavas** [comment]
I believe QMC2 still works with the latest version of MAME, and there are occasional updates from @belegdol to keep it working on current Linux distros.  MAME’s command-line interface and XML output is fairly stable – front-ends don’t need to be updated for every release.

**Comment by linuxsynth** [comment]
UPDATE YOUR VERSION STUPID MORON
YOU ARE WAY BEHIND
