### ISSUE TITLE
request: QT 6 port

### ISSUE THREAD

**Issue by ghost** [qmc2/qmc2-mame-fe#21]
Hi

I would like to request the porting to QT 6 since it offers a big amount of improvements including performance and stability over QT 5.
Also version 6 is out there long enough to start the porting I think.

Is there anything preventing you to port current source code?

**Comment by qmc2** [comment]
> Is there anything preventing you to port current source code?

Yes. It's QtScipt and the XML-stuff.

**Comment by linuxsynth** [comment]
THEN DELETE IT ZND START AGAIN
ARE YOU FINISHED LAZY FUCK?
TOMORROW I WANTNEW QT AND NEW MAME VERSION

OR I CUT YOU OPEN WITH MY KNIFE

**Comment by VR51** [comment]
@qmc2 I hope you are well, Rene, and that you are on the up and up since your stroke a few years ago. You are doing a wonderful job with QMC2; both you and your work are much appreciated by the MAME community. All the best, chap.

**Comment by qmc2** [comment]
Thanks!
