### ISSUE TITLE
Problems with MacOS version 

### ISSUE THREAD

**Issue by cwscws** [qmc2/qmc2-mame-fe#22]
I recently downloaded a precompiled MacOS version of qmc2 2.4.3 and all in all it already works great!

Two problems:
*) MAME emulator config is not shown in options/emulators/global configuration. The window is empty. It also does not show anything when importing the .ini file.

*) Maybe it’s resulting from the above problem but the ROMs folder is recognized correctly only when located in the MAME folder. Tried even a symbolic link of the ROMs folder from an external drive but qmc2 crashes when attempting to load a ROM file. The weird thing: starting MAME directly loading ROMs from the symbolic link ROMs folder works as expected!

**Comment by qmc2** [comment]
> MAME emulator config is not shown in options/emulators/global configuration.
Not again! That bug is thought to be fixed.

With "recently downloaded a precompiled MacOS version of qmc2 2.4.3" you mean to have downloaded it from [estefan3112](https://github.com/estefan3112)?

Also, there is no version 2.4.3, it's 0.243 :).

**Comment by qmc2** [comment]
Oh, and it's actually better to download Qt 5 (official release), git clone QMC2 and [build it](https://wiki.batcom-it.net/index.php/QMC2_FAQ#macOS).

**Comment by cwscws** [comment]
Yes, it’s the prebuild version from estefan3112.

I didn’t build it by myself as I do not have a good grasp of building. Isn’t there a prebuild version available?

**Comment by qmc2** [comment]
> Isn’t there a prebuild version available?

Not an official one. I have no Mac.

**Comment by estefan3112** [comment]
Hi qmc2, great to read from you!
@cwscws : I uploaded a pre-compiled version of qmc2 for Apple Silicon here: 
https://mameonmacs.blogspot.com/2022/04/welcome-back-qmc2.html
The version is:
M.A.M.E. Catalog / Launcher II v0.244, GIT v0.243-14-g112724d69 (Qt 5.15.6, SDLMAME, Darwin arm64)
Please double-check again. In this binary, the options are visible to me. 
Re your problems:
Suggest to move away your /User/Library/Application Support/qmc2 directory or rename it to qmc.bak and try again. Or at least rebuild your options by Tools/Relaunch Setup Wizard.
Best, Stefan

**Comment by cwscws** [comment]
Thank you - but I downloaded this version about a week ago and have the problems described above. Did you build it again now or is it still the same version?

**Comment by cwscws** [comment]
I rebuild it with the Setup Wizard - but the global options window is still empty. The only improvement is that I can correctly access my RoMs folder on an external drive. But I always get the error message that the ROMs folder can not be found - but starting ROMs are working despite this. The error message is annoying.

**Comment by estefan3112** [comment]
Sorry to hear that. I did not rebuild it, it is the same version.
I had this error as well. As far as I can recall, I did another setup, and then the error was gone.
In any way I would try to start all over again by renaming/moving the qmc2 directory in Application Support. Good luck!

**Comment by cwscws** [comment]
Then there must be some kind of bug as I tried to remove the qmc folder several times with no luck.

**Comment by cwscws** [comment]
For what reason ever the error message that the ROM folder could not be found does not appear anymore but the emulator global configuration window is still empty.

**Comment by estefan3112** [comment]
@cwscws - now that qmc2 builds again under Homebrew, I compiled a new version and codesigned it. Available here for download:

https://drive.google.com/file/d/1D1Xs9YYhP10ZEQr_2Qz_9itIjRMK9qek/view?usp=sharing

I do not necessarily expect any change, however, the Homebrew approach to QT5 seems different to MacPorts, so it was at least worth a try.

**Comment by cwscws** [comment]
Many thanx for your efforts! Nevertheless it still does not show the global configuration. I tried to reset the setup several times - no luck. In my opinion it must be something different.

**Comment by cwscws** [comment]
The options template file is set to ~/User/Library/Application Support/qmc2/opt/SDLMAME/template-SDL2.xml
But ther is no opt folder and no SDLMAME folder within the qmc2 folder. This is really weird.

**Comment by cwscws** [comment]
Tried Tools -> Clean up -> Recreate template map but does not work. Got the error message Fatal couldn’t open file. Also changed folder for the xml file to be in qmc2 instead of the non-existing subfolders.

**Comment by estefan3112** [comment]
Aaaaah now I get it! I always forget that there are a bunch of files under the ROOT Library/Application Support! This is installed by the 'sudo make install' command after compilation, and this is apparently missing. I will immediately update the package accordingly and inform you here once again. Many thanks again!

By the way: This is why I failed so far to provide a reasonable installation package for MacOS - the installation of QMC2 is far from trivial...

**Comment by cwscws** [comment]
Nice! I searched the websites for your contact but I didn’t find one. You know, I live not far away from you…

**Comment by estefan3112** [comment]
https://mameonmacs.blogspot.com/2022/04/welcome-back-qmc2.html

New download link online. Apologies for the DS.STORE file. Let's connect via Github :-).

**Comment by cwscws** [comment]
Thank you! Will try that soon! 

Never connected via Github - just connect me…😎

**Comment by cwscws** [comment]
Copying the files to the main Library/Application Support folder didn’t work for some reason. I copied all into ~/Library/Application Support/qmc2 and and works perfect. Even importing the mame.ini into the xml file works perfectly now.

**Comment by estefan3112** [comment]
> Copying the files to the main Library/Application Support folder didn’t work for some reason. I copied all into ~/Library/Application Support/qmc2 and and works perfect. Even importing the mame.ini into the xml file works perfectly now.

I double-checked the Makefile, and the correct folder should be /Library/Application Support/qmc2:
<img width="391" alt="Bildschirmfoto 2022-11-15 um 23 14 57" src="https://user-images.githubusercontent.com/24915559/202036408-758a2790-422d-4754-b85e-bca8b569c9fb.png">
It might be a permission problem, please check whether your user has Read and Write rights on the folder and all subfolders, that might be a problem if not installing via an official installation file.

**Comment by cwscws** [comment]
Thank you for the info! Nevertheless I see no difference having the files in my user folder.

**Comment by qmc2** [comment]
For what it's worth: having the files in the users folder is the way it should be :).

**Comment by estefan3112** [comment]
Hi Rene, in this case I think line 127 of the Makefile needs to be changed, as it currently points to the global Library folder:

DATADIR = /Library/Application Support

Currently there is this split between the global library and the User library.

Cheers, Stefan

**Comment by qmc2** [comment]
No. The DATADIR points to the **initial** directory, when you haven't used it. It only needs a "qmc2.ini" for global settings. After that, everything is read from the user's directory.

**Comment by qmc2** [comment]
In detail it's documwnted here:
https://wiki.batcom-it.net/index.php/The_%27ultimate%27_guide_to_QMC2#Configuration_path

**Comment by cwscws** [comment]
off-topic but using the zip files for flyers, snaps, titles, etc do not work on Mac, except cabinets. All the same files, all files are ok, but not showing them. Is there a trick or is this a bug?

**Comment by qmc2** [comment]
I doubt that this is a bug as it works on Linux and Windows. You probably only forgot to APPLY your settings? Send me you settings (qmc2.ini) if unsure.

**Comment by cwscws** [comment]
I just looked into the qmc2.ini - it’s the same setting for e.g. cabinets.zip and flyers.zip. But the cabinets work, the flyers not. The zip files are ok. Only the cabinets work - all others not (pcs, titles, snaps, marquees, etc.). I noticed that only the cabinets have a zip setting in the config, maybe this is causing it?

**Comment by estefan3112** [comment]
Hi @cwscws, this is definitely an error on your side: All dirs and zip files work as expected. **You need to switch between dirs and zip files by pressing this button back and forth.** All the zip files work for me as well as directories.

![Bildschirmfoto 2022-11-21 um 22 25 38](https://user-images.githubusercontent.com/24915559/203161689-8730c27f-3cd2-4b79-9ec5-dc43411c1d02.jpeg)

**Comment by cwscws** [comment]
Ok, then there is something going on - I only have the Zip-Switch at cabinets. No such switches at the others!?

**Comment by cwscws** [comment]
Ok this was confusing but my fault - the button does not change color so I did not realize this this changes the behavior if it’s a file or directory. I would request the it changes color to see that immediately.

I did not find this in the online manual or did I miss it?

Nevertheless it’s working now. Many thanks for the help!

**Comment by cwscws** [comment]
Never mind, will figure this out by myself. It’s a little bit hard for me to get used to ancient DOS like setup experience.

**Comment by cwscws** [comment]
One last question: is it possible to use an artworks.zip (or artwork.zip) instead of unpacking the zip file in /artwork?

**Comment by estefan3112** [comment]
> Ok this was confusing but my fault - the button does not change color so I did not realize this this changes the behavior if it’s a file or directory. I would request the it changes color to see that immediately.
> 
> I did not find this in the online manual or did I miss it?
> 
> Nevertheless it’s working now. Many thanks for the help!

I expected that and wanted to insist that you press this button once again - because it was also confusing to me in the first place.

**Comment by estefan3112** [comment]
> Never mind, will figure this out by myself. It’s a little bit hard for me to get used to ancient DOS like setup experience.

Nonononono! If you want DOS-like experience, I invite you to configure mame from MAMEUI or Attract Mode. QMC2 is QT luxury !!! :-)

**Comment by estefan3112** [comment]
> One last question: is it possible to use an artworks.zip (or artwork.zip) instead of unpacking the zip file in /artwork?

No, that would be a wrong approach! Please read my post on MAME Artworks - these are layout files and graphics packed into one zip per game. It is a single zip approach, so everything is already compressed.

https://mameonmacs.blogspot.com/2017/02/porting-retropie-artwork-to-official.html

But if you download from my repository, you need to zip them individually, as explained on ma Github page.

**Comment by cwscws** [comment]
Many thanx for the info! Of course, qmc2 is much more elegant than other solutions - but still extremely complex. I understand the thing with artworks.zip - I found this collection over at archive.org and I already noticed that it must be unzipped in /artwork to get it working. Nevertheless it would be even more elegant if it could be kept at one single zip.

**Comment by qmc2** [comment]
And, BTW, **any** collections you have and want to display (not the one that QMC2 "supports") can be added as "additional artwork classes" (description is in the wiki). So yes, this **is** supported!

**Comment by cwscws** [comment]
The zip file with the zip file really works?

**Comment by qmc2** [comment]
No.

**Comment by cwscws** [comment]
Yes, because artworks.zip contains zip files of each ROM having an overlay.

**Comment by qmc2** [comment]
Then that's for something else (i.e. like estefan said). I just told you that you can have as many "picture sources" as you like.

Let's really close this "issue".

**Comment by estefan3112** [comment]
@cwscws - I think that you oversee a crucial issue: While Flyers, Marquees etc. are for the frontend (qmc2), the Artworks are in-game bezels (within MAME), but not for the frontend! This is why they need to be treated differently! 

@qmc2 - Rene sorry for this add-on, I wanted to make this clear.

**Comment by cwscws** [comment]
Is there a discussion group, a forum or discord, where qmc2 can be discussed?

**Comment by qmc2** [comment]
It's all shown in the about-box :)... https://forums.bannister.org/ubbthreads.php?ubb=postlist&Board=12&page=1 is the discussion form.
