### ISSUE TITLE
feature request: software list machine filter

### ISSUE THREAD

**Issue by ghost** [qmc2/qmc2-mame-fe#23]
Hello qmc2

I'm having trouble to run software list games. I don't know how to do it at all.
Can you tell me the steps to do ?
And how to see all games of a specific software list?

**Comment by qmc2** [comment]
See here:
https://wiki.batcom-it.net/index.php/The_%27ultimate%27_guide_to_QMC2#Software_lists

If you should have questions afterwards, come back.

**Comment by tranzedude** [comment]
This frotend really rocks! It's definitely the best MAME frontend out there.
Thanks a lot for the many docs.

- Can I request a small feature for the machine list, more specifically filtering?

We now have in the machine list 3 main type of machines:

- games (no symbol)
- devices (symbol "D")
- BIOS (symbol "B")

Could you add the symbol "S" for machines that support software list(s)?
In this way it's easy to find them. I believe the XML shows if a machine supports software list(s) or not.
If a machine has one or more <softwarelist> tags, it means it supports software list(s).

- In addition I would like to request a machine list filter (which can now be made) which consist of 4 "filter" buttons: 

- game
- device (symbol "D")
- BIOS (symbol "B")
- software list machine (symbol "S)

Those buttons could be put in the toolbar above the machine list but preferrable a new toolbar called "filters" could be made for it.
If a button is pressed, it shows the filtered machines in the machine list.
If a button is unpressed, it removes the filtered machines from the machine list.
So a button can be in pressed or unpressed state, that should be indicated in the GUI
In this way we can show/hide the games, devices, BIOSes and software list machines from the machine list.

If both features are implemented and a user wants for example all machines that support software list(s), he just can do this:

- Unpress the buttons for game, device and BIOS
- the machine list now only shows the machines supporting software list(s)



Thank you very much!

**Comment by tranzedude** [comment]
Is there any interest in adding this?
I can't know if you don't answer :)

**Comment by tranzedude** [comment]
Anybody out there? ...

**Comment by cuavas** [comment]
> Anybody out there? ...

This kind of behaviour is going to annoy developers.  It doesn’t help you.

**Comment by tranzedude** [comment]
> > Anybody out there? ...
> 
> This kind of behaviour is going to annoy developers. It doesn’t help you.

GO FUCK YOURSELF AND STOP TELLING OTHER WHAT TO DO
PIECE OF SHIT

AND TO THE BRAINDEAD DEVELOPER OF QMC2
READ YOUR FUCKING SHIT OR GO FUCK YOURSELF TOO

**Comment by tranzedude** [comment]
ANSWER

**Comment by tranzedude** [comment]
ANSWER

**Comment by tranzedude** [comment]
ANSWER

**Comment by tranzedude** [comment]
ANSWER

**Comment by tranzedude** [comment]
ANSWER

**Comment by tranzedude** [comment]
ANSWER

**Comment by tranzedude** [comment]
ANSWER

**Comment by tranzedude** [comment]
ANSWER

**Comment by tranzedude** [comment]
ANSWER

**Comment by tranzedude** [comment]
ANSWER

**Comment by tranzedude** [comment]
ANSWER

**Comment by tranzedude** [comment]
ANSWER
