### ISSUE TITLE
feature request: favorites ROM state

### ISSUE THREAD

**Issue by ghost** [qmc2/qmc2-mame-fe#24]
Hello qmc2

The favorites list is a very usefull feature, however it could be enhanced a bit more to be more usable, especially to see the ROM state of the games (since the favorites list are the games you play the most and therefore you should see their ROM state).

=> In the machine list there is a green icon indicating if a ROM state has passed OK.
However, if you use only your current favorites list because you only play those games, you can't see the ROM state icon in the favorites list. So you don't know if the games are OK or not if you are in the favorites list.
I would like to request the same ROM state icons (from the machines list) to appear in the favorites list. Please read my next request why this is usefull.

![afbeelding](https://user-images.githubusercontent.com/118472172/202775193-e29c7391-c465-4cbf-84b0-f7bfa67da51e.png)

=> I would like to request, in addition to ROM state icons in the favorites list, a feature to do a ROM state check on ALL games in the current favorites list. So it should loop through all games of the favorites list and do a ROM state check on each of them and display the correct status icon (green, ... as in screenshot above)

If both features are added, users can go to their favorites list (for each MAME update), do a ROM state check on the complete favorites list and see which games don't have a green icon anymore.
It's very convenient then to see the ROMs that need to be updated.
Currently the favorites list can't give you this information as it only show a list of games without any additional information. You also currently can't check the whole favorites list for ROM state passes.
The features I request can make it a more powerful tool, especially to migrate your favorites list from MAME to MAME update and easily see what games need to be updated.

=> I also would like to ask where the favorites list is stored on my hard drive when we save it?
This in order to make a backup.

Thank you very much!

**Comment by qmc2** [comment]
2) Press F10.

3) See <<config_path>>/sw-state-cache/*.ssc

**Comment by tranzedude** [comment]
> 2. Press F10.

Do you mean pressing F10 while in the favorites tab should do a ROM state check on all the favorite games of the whole list?
If this is true, F10 doesn't do anything here :(

**Comment by tranzedude** [comment]
I also would like to request a status bar for the favorites list that shows how many favorite games are in the current list.

**Comment by qmc2** [comment]
_F10 Check software-states (**only available when the software-list detail is active**)_

**Comment by qmc2** [comment]
2. A misunderstanding. Sorry.
3. You are asking too much :). Basically the machine will be ignored / seen as "unknown"

**Comment by tranzedude** [comment]
> 2. A misunderstanding. Sorry.

You mean by this there is NO way to do a ROM State check on the complete favorites games list? (which is what I requested as feature)

>     3. You are asking too much :). Basically the machine will be ignored / seen as "unknown"

I need to ask a lot because you answer so shortly I can't understand it :)
I'm not a developer so I can't look in the source code :(

**Comment by tranzedude** [comment]
Are you interested in adding features we request?
At the moment, I have the impression you don't want to add anything...
Please explain so I don't waste your (and my) time :)

Thanks

**Comment by qmc2** [comment]
2. Unfortunately, no.

I'm (currently) not interested because you have the opportunity to set **ranks**.

**Comment by tranzedude** [comment]
I AM NOT INTERESTED IN YOUR SHIT FRONTEND TO
