### ISSUE TITLE
bug: qmc2 arcade black screen

### ISSUE THREAD

**Issue by tranzedude** [qmc2/qmc2-mame-fe#25]
Hi

For some reason qmc2 arcade displays a black screen and nothing else.
I tested with mame 0.249 from mamedev.org with latest qmc2 on windows 10.

**Comment by qmc2** [comment]
Yes. qmc2-arcade does not work, only theme "darkone" works somewhat.

**Comment by tranzedude** [comment]
Ow ok!
Are there plans to fix it?
What exactly does qmc2-arcade do because I have never seen it.

**Comment by qmc2** [comment]
Not now.

See here: https://wiki.batcom-it.net/index.php/The_%27ultimate%27_guide_to_QMC2#Arcade_mode
