### ISSUE TITLE
question: MAME command line string

### ISSUE THREAD

**Issue by tranzedude** [qmc2/qmc2-mame-fe#26]
Hi

=> I"m trying to find out if there is a way in qmc2 to enter a MAME command line string that will be passed to all games when they are run.
So I want to choose the command line string myself and not using the built-in options in qmc2.

Is this possible somewhere?

=> I also want to ask if the MAME configuration applied to all games is the one found in Options -> Emulator -> Global Configuration? Just to be 100% sure :)

**Comment by qmc2** [comment]
1) Yes, from "outside" QMC2. Leave all options at their defaults and feed "mame.ini".

2) Yes, that's the "global configuration". Besides this, each game / machine can have its "local configuration".
