### ISSUE TITLE
bug: software list games not added to favorites

### ISSUE THREAD

**Issue by ghost** [qmc2/qmc2-mame-fe#27]
Hi

While testing the favorites feature, I saw ONLY games available in the machine list can be added to favorites.
But if you want to add a software list game, it is NOT added at all to the favorites list.

Steps to reproduce:

1. Select machine for example "nintendo entertainment system / famicom (NTSC)"
2. Go to software list tab
3. Select any game from the software list tab
4. Right click the game and choose 'add to favorites"
5. The game is not added to the favorites list (also not in the mame.fav file)

**Comment by qmc2** [comment]
This is no bug!

**Comment by tranzedude** [comment]
If it's not a bug, why is no software list game added to the favorites list?  I tried many of them and none is added.

**Comment by tranzedude** [comment]
Can anybody explain?

**Comment by qmc2** [comment]
Yes. Because software-list games are added to another favorites list. Look under the current software-list, there's a "favorites" as well, and a "search" BTW...

**Comment by tranzedude** [comment]
Are those stores in one of the .db files because I can't find a text file of the favorites? (compared to the favorites file of the normal games)

**Comment by qmc2** [comment]
Yes. It is stored in mame-user-data.db.
