### ISSUE TITLE
feature request: game category/INI file/custom folder support

### ISSUE THREAD

**Issue by tranzedude** [qmc2/qmc2-mame-fe#28]
Hi

I would like to request a feature that doesn't exist at all in qmc2: the category view for the games.

The following features were present in MAMEUI but none of them are in qmc2 (AFAIK):

- category view: games are sorted by year, manufacturer, ... extracted from the mame XML

- INI file view: INI files appear in the category view, which can be created by the user using text editor and then copying them to a folder that is read by qmc2. Many files are created here:

 https://www.progettosnaps.net/support/

- custom folder: the category view can have a "custom" folder to which the user can drag-and-drop games in order to make a custom folder of games (those are stored to INI file too)

There could be made an additional tab in qmc2 for this category view (which can be hidden)

Please look at MAMEUI for examples (and the red part of the UI):

https://arcade.mameworld.info/messui/index.html

![afbeelding](https://user-images.githubusercontent.com/118472172/203175959-d383b0ff-e7c0-4b8d-bc31-850caffc1a2c.png)

**Comment by qmc2** [comment]
The category view **does** exist, when you have some source (catver.ini / category.ini) for categories. However, these files might not be enough...

**Comment by tranzedude** [comment]
Where does the category view appear then? In an existing tab(which one), a new tab, ...?

What is meant by "However, these files might not be enough..."? 

Is it possible to explain in your answer a bit more so I can understand what you mean?
You answer very shortly and in a way I have virtually no information about what you mean.
I'm a beginner using qmc2 and can't read your mind :)

**Comment by tranzedude** [comment]
But that's still not the complete feature I mean: I mean a category view that groups games by their own data too like year, manufacturer, ...
No INI files are needed for this because it's in the XML of MAME. This is not inside qmc2 I think.

Are it catver and category I have to specify here and then a new tab or widget will appear? (for now I don't see it/don't know where it is)

![afbeelding](https://user-images.githubusercontent.com/118472172/203388736-9cdd3936-7905-43fc-be6a-7fec0a1d0116.png)

**Comment by tranzedude** [comment]
So this request is rejected as well? I mean the part of a category view based on MAME XML itself (year, manufacturer, CPU, ... )
