### ISSUE TITLE
The software list is empty.

### ISSUE THREAD

**Issue by Stibax** [qmc2/qmc2-mame-fe#31]
HI, 
i have installed from AUR the latest qmc2, and i have set all the path in configuration with the latest mame and rom set (0254), but the software list is always empty. Can someone help me, or it's a known bug? 
![qmc2](https://github.com/qmc2/qmc2-mame-fe/assets/49286497/c969043b-5185-4940-be8f-29e976a0df16)

![qmc2_2](https://github.com/qmc2/qmc2-mame-fe/assets/49286497/4d64118e-b75a-4449-a1ee-839af6e2e90a)

Thanks.

**Comment by belegdol** [comment]
Does anything happen if you click on the refresh button in the software list tab?

**Comment by estefan3112** [comment]
Hi, long time ago, I did a short intro to software lists in QMC2:
https://mameonmacs.blogspot.com/2016/05/starting-with-mess-in-qmc2.html
With this configuration, software lists still work for me here. Your hash path seems wrong according to the screenshots, and from my own testing, it seems that QMC2 expects the romfiles in subfolders of the roms directory. Hope this helps.
