### ISSUE TITLE
Mac Updates?

### ISSUE THREAD

**Issue by adamesq** [qmc2/qmc2-mame-fe#32]
MacUpdater shows some update info for this, but can't track down the files. The numbering on both makes little sense, but just checking!
<img width="577" alt="Screenshot 2023-08-05 at 11 29 17 AM" src="https://github.com/qmc2/qmc2-mame-fe/assets/34196956/140af704-f850-4d96-9420-77bb6fa26a1c">

**Comment by belegdol** [comment]
I do not have sufficient rights to make a release, but please try this out:
https://github.com/belegdol/qmc2-mame-fe/actions
There is an artifact for macos-14/aarch64 and macos-12/x86_64.

**Comment by belegdol** [comment]
Now available from this repo as well:
https://github.com/qmc2/qmc2-mame-fe/actions/workflows/ci-macos.yml
