### ISSUE TITLE
request: build with history.xml

### ISSUE THREAD

**Issue by ghost** [qmc2/qmc2-mame-fe#34]
Hi

Could you please release a new build (in the tags on github) that has history.xml support included?
I want to test it and report possible bugs.
I'm not familiar with compiling qmc2...

**Comment by belegdol** [comment]
I do not have sufficient rights to make a release, but please try this out:
https://github.com/belegdol/qmc2-mame-fe/actions
There is an artifact for ubuntu-22.04/x86_64, macos-14/aarch64 and macos-12/x86_64.

**Comment by belegdol** [comment]
I am trying to get windows running as we speak.
Technically there is a fork since I need one for the PRs. Having said that, I can realistically only fix small things.

**Comment by belegdol** [comment]
Yes, the lead developer unfortunately passed away last year.

**Comment by belegdol** [comment]
I think updating to qt-6 might be beyond my coding skills unfortunately.

**Comment by belegdol** [comment]
Looks like there is no QtWebEngine for Windows, so no Windows builds are possible from git master. Sorry.

**Comment by belegdol** [comment]
Switch to qtwebengine was made after 0.243. Before that qtwebkit was used, for which msys package is available.
For qtwebengine the build would need to be made with msvc. I will have a look if this can be done.

**Comment by belegdol** [comment]
QtWebKit is no longer maintained and full of security issues. As for what it is used for, notes tab is one example. I will look into possible solutions but it is going to take some time. I can maybe make a 0.243+fixes branch over at my fork in the meantime.

**Comment by belegdol** [comment]
Very preliminary windows build:
https://github.com/belegdol/qmc2-mame-fe/actions/runs/7966316077/job/21747346457
Uses ancient qr 5.15.2 because this is what is available prebuilt.

**Comment by belegdol** [comment]
Well Qt5 beyond 5.15.2 are only distributed as source. So instead of just downloading it as it is done currently, Qt would need to be built from source first, which would burn through the 2000 minutes available for free in no time (or 2000 minutes really) - if it even were enough to build heavy dependencies like qtwebengine more than a handful of times.

**Comment by cuavas** [comment]
There are per-user resource limits, but you can’t see how close to hitting the limit you are.  If you exceed the limits, your account can be flagged for “abuse” and you will be unable to trigger GitHub Actions CI jobs, even for your pull requests against other projects.  This has happened to MAME contributors (e.g. @0kmg).  It’s particularly easy to hit the storage limit for workflow artefacts with large projects if you aren’t careful.

There’s no appeal process, and they won’t even tell you what limits you exceeded.  They justify this by saying if they told you what the limits are, you could try to sidestep them.

Some users associated with “halo projects” are exempt from the limits.  There’s no way of knowing whether your account is exempt from limits (besides generating enough workflow artefacts to exceed the normal limits and seeing if you get banned).

It’s very opaque, and you need to tread carefully if you depend on being able to run CI jobs.
