### ISSUE TITLE
Currently does not build in Mac Silicon, right?

### ISSUE THREAD

**Issue by estefan3112** [qmc2/qmc2-mame-fe#5]
Hi, so great to see you back! 
I just tried my luck on my M1 Mac Mini, and the compiler returns me an error. Seems that the Apple Silicon platform is not configured (yet). Am I correct?

Configuring build of QMC2 v0.242

 qmake-qt5 -makefile -o Makefile.qmake -spec macx-g++ VERSION=0.242 QMC2_MINGW=0 SDL=2 TARGET=qmc2-sdlmame CONFIG+=warn_off CONFIG+=release 'DEFINES+=QMC2_SDLMAME QMC2_VERSION=0.242 BUILD_OS_NAME=Darwin BUILD_OS_RELEASE=21.4.0 BUILD_MACHINE=arm64 PREFIX=/usr/local DATADIR="/Library/Application:Support" SYSCONFDIR="/Library/Application:Support" QMC2_JOYSTICK=1 QMC2_PHONON=0 QMC2_MULTIMEDIA=1 QMC2_FADER_SPEED=500 QMC2_MAC_UNIVERSAL=0 QMC2_BROWSER_EXTRAS_ENABLED QMC2_BROWSER_PLUGINS_ENABLED QMC2_BROWSER_JAVA_ENABLED QMC2_BROWSER_JAVASCRIPT_ENABLED QMC2_YOUTUBE_ENABLED QMC2_BUNDLED_MINIZIP QMC2_BUNDLED_ZLIB' qmc2.pro 

Info: creating stash file /Users/.............................../qmc2-mame-fe-0.242/.qmake.stash 
Project ERROR: Cannot run compiler '/Applications/Xcode.app/Contents/Developer/usr/bin/g++'. Output:
Apple clang version 13.1.6 (clang-1316.0.21.2) 
Target: unknown-apple-darwin21.4.0 
Thread model: posix
 InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin 
clang: error: invalid arch name '-arch -isysroot' 
clang: warning: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk: 'linker' input unused [-Wunused-command-line-argument]
Maybe you forgot to setup the environment? 
make: *** [Makefile.qmake] Error 3

**Comment by qmc2** [comment]
To be honest, I have no idea :). That is, I do not have access to a newer Mac... only a x86 one. So yes, it's probably something platform and compiler related. That's why I said "only Linux" is supported at the moment.

But while we're at it, can I get remote access (via ssh) to your system? Some user account, no root access for now (for installation I would need i, though)... since we're both German speaking (?) you can email me about it - in German.

**Comment by estefan3112** [comment]
Hello, many thanks for the feedback! Btw I tried my luck on an x64 Mac in Catalina, and here I also fail on the missing QT Webkit packages - they are no longer available in qt@5. I do not recall correctly - isn't there an option to build QMC2 without the webkit stuff? I forgot through the years.
Please refer to estefan3112 at gmail dot com and German is perfectly fine - I live in Vienna :-).

**Comment by qmc2** [comment]
Webkit is not / no longer available in Qt 5? No no, it is.

Yep, I'll come back to you then. But I have other things to do first! Thanks.

**Comment by qmc2** [comment]
I've sent you two emails... did they reach you?

**Comment by estefan3112** [comment]
Thank you so much. Now answered!

**Comment by qmc2** [comment]
I'll close this issue sine we now know what to do to make it work... see https://github.com/qmc2/qmc2-mame-fe/issues/9

**Comment by estefan3112** [comment]
Just for the records how this builds in macOS Catalina for x64:
- SDL Framework (as for MAME)
- MacPorts qt5 @5.15.3_0 (including dependencies)
- MacPorts qt5-qtwebkit @5.9.2_2 (including dependencies)
Homebrew does no longer provide QT-Webkit, but MacPorts does
Next: Look into the situation on Mac Silicons :-).

**Comment by estefan3112** [comment]
Solved! The latest code also builds an Apple Chips Binary under Monterey with the same build prerequisites as reported for x64.
Note to self: Never forget sudo make install on Macs. The build looks ok so far. Now testing.

**Comment by sl1pkn07** [comment]
qt5-webkis is begin droped from all distributions/homebrew due a lack updates since 3years and zero patch to solve the CVEs remain/new in the code

please consider use other thing in qt5 build. seems Qt6 webkit port still keep updated

greetings

**Comment by estefan3112** [comment]
> qt5-webkit is begin droped from all distributions/homebrew due a lack updates since 3years and zero patch to solve the CVEs remain/new in the code
> 
> 
> 
> please consider use other thing in qt5 build. seems Qt6 webkit port still keep updated
> 
> 
> 
> greetings

Hello, as far as I understand, the latest version has already moved fully to qtwebengine. See the separate open issue. Cheers!
