### ISSUE TITLE
Some values not showing in global options.

### ISSUE THREAD

**Issue by N3tFX** [qmc2/qmc2-mame-fe#8]
I have noticed that for some text input fields, the values do not appear most of the times, even thought the value is set.
I have noticed this in the global rompath field in the: _Emulator tab > Global configuration sub-tab > Search Paths > rompath_. If I close and reopen the windows many times it sometimes shows up, but it should load the value from the configuration file when the options window is opened.

**Comment by qmc2** [comment]
It's clearly shown here. Probably a style thing?

**Comment by qmc2** [comment]
But this is true for Windows...

**Comment by N3tFX** [comment]
I am on linux with gnome and I don't use any themes. It happens only to QMC2 and not others KDE apps that I use in the same machine. Weird.

**Comment by N3tFX** [comment]
Also, that field is the one that I've noticed. Maybe it's happening to other fields also.

**Comment by qmc2** [comment]
Well, interestingly not here, that is, openSUSE Leap 15.1... thanks for the heads up! I'll check tomorrow or at least "this week" since I have a little time (Easter). Not today, though.

**Comment by qmc2** [comment]
Also local / machine options are affected. But again, not on "my" Linux. Strange.

Didn't find it yet. These emu-option-types should be affected: QMC2_EMUOPT_TYPE_COMBO, *_COLOR, *_FILE, *_DIRECTORY and *_STRING.

**Comment by estefan3112** [comment]
This happens to me in MacOS as well. For testing purposes, I set a custom rom-path and a custom ini-path, storing the values with the store icon:

![Screenshot 2022-04-11 at 20 50 44](https://user-images.githubusercontent.com/24915559/162809257-c18295d2-3adc-49f6-978e-636488dc1ff5.png)

After a restart of QMC2, the values are gone in the UI, but they are in qmc2.ini!
![Screenshot 2022-04-11 at 20 52 32](https://user-images.githubusercontent.com/24915559/162809565-76e48f39-f539-45e3-a2cc-25740317ac87.png)

**Comment by qmc2** [comment]
Okay, thanks for the info... as expected.

**Comment by estefan3112** [comment]
Add-on: It seems that this applies to all options in my configuration. 
Another example: I switch to Video/Windows (from default fullscreen), and after restarting QMC2, the option is no longer visible, but it is in qmc2.ini:
Configuration\Global\window=true
But the frontend does not show me the option as activated after a restart.

**Comment by qmc2** [comment]
This is driving me nuts. I meanwhile figured out, that for "newer Qt" the amount of time it goes through the code (= sets the values in this dialog) is 1 and it doesn't realize the default values, whereas in "older Qt" (for instance my Qt 5.9) it's 2 and the defaults are loaded. That's strange enough.

In both Qt versions it doesn't set the description and so on correctly (however, that's not so important).

I need more time to fix it...

**Comment by qmc2** [comment]
Okay, now the descriptions etc. are back... at least something :),

**Comment by qmc2** [comment]
At least the StarDelegate example converted to use a QTreeWidget (as in case of QMC2's emu options) instead of a QTableView seems to work in both Qt bersions, so it can't be much...

**Comment by qmc2** [comment]
Wow, after "endless" sessions of changing _src/emuopt.cpp_ I finally did this little commit and it seems to be working again:
https://github.com/qmc2/qmc2-mame-fe/commit/66b0c0a406dc5a1e3c235c125672ee3fccad17c5

**Comment by N3tFX** [comment]
I just tried it and it seems to work. At least in Debian.

**Comment by qmc2** [comment]
Yeah, this really seems to have fixed it - strange, but who cares :). It works on Windows, too.

Thanks! I'm waiting for an info if it also works on macOS, and when, I'll close it.

**Comment by estefan3112** [comment]
Very nice results on MocOS here! I have a Windows PC here, but no build environment on it.

**Comment by qmc2** [comment]
Thanks, that's nice. Then I'll close the issue!
